FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN pip3 install --upgrade pip
RUN pip3 install "uvicorn[standard]"
RUN pip3 install requests
COPY ./requirements.txt /code/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt
COPY api ./

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]

